# Define default logging configuration
# The following common command line options/environment variables can be used to
# manage logging:
# --logging.level.com.fortify=TRACE
# --logging.file.name=FortifyVulnerabilityExporter.log   # Enable logging to file, write to given file name
# --logging.file.path=/var/log                           # Enable logging to file, default file name is spring.log
logging:
  level:
    org.springframework: WARN
    org.quartz: WARN
    com.fortify: INFO

spring:
  config:
    import: optional:file:${export.config:FortifyVulnerabilityExporter.yml}
  profiles:
    active: default, ${export.from}
  main:
    web-application-type: NONE

# Set default export directory to .
# This is overridden to /export by the Docker image
export.default.dir: .
