export:
  from: fod
  to: json.gitlab.dast

fod:
  scopes: view-apps, view-issues, view-reports
  release:
    embed:                                          # Load dynamic scan summary as required for GitLab output
      - propertyName: dynamicScanSummary
        uri: /api/v3/scans/{currentDynamicScanId}/summary
        embedIf: currentDynamicScanId!=null
      - propertyName: siteTree
        uri: /api/v3/scans/{currentDynamicScanId}/site-tree
        embedIf: currentDynamicScanId!=null
        onError: LOG_WARN                           # Site tree may not be available, so we just log a warning

  vulnerability:
    filterParam: scantype:Dynamic                   # Have FoD return only static issues 
    embed:                                          # Also load details and recommendations as required for GitLab output
      - subEntity: details
      - subEntity: recommendations
      - subEntity: request-response

json.gitlab.dast.output:
  stdout: false                                     # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                      # Useful for debugging, disable for optimal performance
  file:   ${CI_PROJECT_DIR:.}/gl-fortify-dast.json  # Write to CI_PROJECT_DIR if defined, current directory otherwise
    