# See FortifyVulnerabilityExporter documentation for FoD connection settings and release selection

export:
  from: fod
  to: json.gitlab.sonatype

fod:
  release:
    embed:                                          # Load open source scan summary as required for GitLab output
      - propertyName: openSourceScanSummary
        uri: /api/v3/scans/{currentStaticScanId}/summary # TODO use actual open source scan rather than static scan
        embedIf: currentStaticScanId!=null
  vulnerability:
    filterParam: category:Open Source               # Have FoD return only open source issues # TODO Change this to scanType 
    embed:                                          # Also load details and recommendations as required for GitLab output
      - subEntity: details
      - subEntity: recommendations

export.dir: ${CI_PROJECT_DIR:${export.default.dir}} # Unless overridden, use CI_PROJECT_DIR if defined, otherwise default export dir
json.gitlab.sonatype.output:
  stdout: false                                     # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                      # Useful for debugging, disable for optimal performance
  file:   ${export.dir}/gl-fortify-depscan.json     # Output file