# See FortifyVulnerabilityExporter documentation for FoD connection settings and release selection

export:
  from: fod
  to: json.sonarqube.sast

fod:
  vulnerability:
    filterParam: scantype:Static     # Have FoD return only static issues 

json.sonarqube.sast.output:
  stdout: false                    # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                     # Useful for debugging, disable for optimal performance
  file:   ${defaultExportDir}/sq-fortify-sast.json