# See FortifyVulnerabilityExporter documentation for SSC connection settings and application version selection

export:
  from: ssc
  to: json.gitlab.sast

ssc:
  version:
    embed:
      - subEntity: currentStaticScan
        onError: LOG_INFO
  vulnerability:
    filterParam: ISSUE[11111111-1111-1111-1111-111111111151]:SCA   # Have SSC return only SCA issues
    embed:                                                         # Also load details as required for GitLab output
      - subEntity: details                                                 

json.gitlab.sast.output:
  stdout: false                                     # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                      # Useful for debugging, disable for optimal performance
  file:   ${CI_PROJECT_DIR:.}/gl-fortify-sast.json  # Write to CI_PROJECT_DIR if defined, current directory otherwise
  