# See FortifyVulnerabilityExporter documentation for SSC connection settings and application version selection

export:
  from: ssc
  to: csv

# ssc:
  # vulnerability:
    # embed:                    # Load extra data, depending on what data you want to include in output
    #   - subEntity: details

csv:
  output:
    stdout: false               # Disabled by default to avoid vulnerability data being exposed through log files
    file:   ${EXPORT_DIR:.}/${applicationVersion.project.name}-${applicationVersion.name}.csv
  fields:
    source: Fortify SSC
    engineType: $[vuln.engineType]
    id: $[vuln.id]
    issueInstanceId: $[vuln.issueInstanceId]
    category: $[vuln.issueName]
    file: $[vuln.fullFileName]
    line: $[vuln.lineNumber]