# See FortifyVulnerabilityExporter documentation for SSC connection settings and application version selection

export:
  from: ssc
  to: json.gitlab.sast, json.gitlab.dast, json.gitlab.sonatype

ssc:
  version:
    embed:
      - subEntity: currentStaticScan
        onError: LOG_INFO
      - subEntity: currentDynamicScan
        onError: LOG_INFO
      - subEntity: currentSonatypeScan
        onError: LOG_INFO
  vulnerability:
    embed:                                             # Also load details as required for GitLab output
      - subEntity: details                                                 

json.gitlab.sast.output:
  stdout: false                                        # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                         # Useful for debugging, disable for optimal performance
  file:   ${CI_PROJECT_DIR:${defaultExportDir}}/gl-fortify-sast.json     # Write to CI_PROJECT_DIR if defined, current directory otherwise
  
json.gitlab.dast.output:
  stdout: false                                        # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                         # Useful for debugging, disable for optimal performance
  file:   ${CI_PROJECT_DIR:${defaultExportDir}}/gl-fortify-dast.json     # Write to CI_PROJECT_DIR if defined, current directory otherwise
  
json.gitlab.sonatype.output:
  stdout: false                                        # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                         # Useful for debugging, disable for optimal performance
  file:   ${CI_PROJECT_DIR:${defaultExportDir}}/gl-fortify-depscan.json  # Write to CI_PROJECT_DIR if defined, current directory otherwise
  