# See FortifyVulnerabilityExporter documentation for SSC connection settings and application version selection

export:
  from: ssc
  to: json.gitlab.sonatype

ssc:
  version:
    embed:
      - subEntity: currentSonatypeScan
        onError: LOG_INFO
  vulnerability:
    filterParam: ISSUE[11111111-1111-1111-1111-111111111151]:SONATYPE   # Have SSC return only Sonatype issues
    embed:                                                              # Also load details as required for GitLab output
      - subEntity: details                                                 

json.gitlab.sonatype.output:
  stdout: false                                        # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                         # Useful for debugging, disable for optimal performance
  file:   ${CI_PROJECT_DIR:.}/gl-fortify-depscan.json  # Write to CI_PROJECT_DIR if defined, current directory otherwise
  