name: doc-resource-updater

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'
  push:
    branches:
      - main

jobs:
  update-repo-doc-resources:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Update documentation resources
      run: bash doc-resources/update-repo-docs.sh

    - uses: peter-evans/create-pull-request@v4
      with:
        commit_message: 'docs: Auto-update documentation resources' 
        branch: auto-doc-updates
        delete-branch: true
        title: 'Update documentation resources'
        labels: |
          automated pr
          documentation
        
        